### Sign up a user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}


### Sign in a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}


### Get the currently signed in user
GET http://localhost:3000/auth/whoami


### Sign Out a user
GET http://localhost:3000/auth/signout


### Find all users
GET http://localhost:3000/auth


### Find a user by id
GET http://localhost:3000/auth/125


### Update an user
PATCH http://localhost:3000/auth/5
Content-Type: application/json

{
    "password": "newPassword"
}


### Delete a user
DELETE http://localhost:3000/auth/2
